/**
 * Site Configuration
 *
 * This file contains all site-specific settings that can be customized
 * for different niches (Fashion, Fitness, Food, Tech, etc.)
 *
 * GENERATED FILE - Do not edit manually
 * Generated by: Site Generator
 * Generated at: 2025-11-06T14:56:36.155Z
 */

import { getLanguageConfig, type SupportedLanguage } from './languages';

export interface SiteConfig {
  // Basic Site Information
  site: {
    name: string;
    tagline: string;
    description: string;
    url: string;
    wordpressUrl: string;
    language: string;
    locale: string;
  };

  // Brand Identity
  brand: {
    colors: {
      primary: string;
      secondary: string;
      accent: string;
      background: string;
      text: string;
      textSecondary?: string;
    };
    typography: {
      headingFont: string;
      bodyFont: string;
    };
    logo?: {
      text: string;
      subtitle?: string;
    };
  };

  // Content Settings
  content: {
    postsPerPage: number;
    relatedPostsCount: number;
    excerptLength: number;
    featuredImageRatio: string;
    showAuthor: boolean;
    showDate: boolean;
    showCategories: boolean;
    showTags: boolean;
  };

  // Navigation
  navigation: {
    header: Array<{
      label: string;
      href: string;
      external?: boolean;
    }>;
    footer: {
      sections: Array<{
        title: string;
        links: Array<{
          label: string;
          href: string;
          external?: boolean;
        }>;
      }>;
    };
    menuCategories?: Array<{
      name: string;
      slug: string;
    }>;
  };

  // Social Media
  social: {
    pinterest?: string;
    instagram?: string;
    facebook?: string;
    twitter?: string;
    youtube?: string;
    tiktok?: string;
    email?: string;
  };

  // Analytics & Tracking
  analytics: {
    googleAnalytics?: string;
    googleAdsense?: string;
    facebookPixel?: string;
    pinterestTag?: string;
  };

  // Legal Information
  legal: {
    companyName: string;
    contactEmail: string;
    country: string;
    jurisdiction: string;
  };

  // Hero Section (Homepage)
  hero: {
    title: string;
    subtitle: string;
    backgroundImage: string;
    cta?: {
      text: string;
      href: string;
    };
  };

  // Persona / About Page
  persona?: {
    name: string;
    role: string;
    bio: string;
    story: string;
    expertise: string[];
    image?: string;
    quote?: string;
    achievements?: string[];
  };

  // Features / Highlights
  features?: Array<{
    title: string;
    description: string;
    icon?: string;
  }>;

  // Custom Scripts/Code Injection
  customScripts?: {
    headScripts?: string;
    bodyStartScripts?: string;
    bodyEndScripts?: string;
  };

  // SEO Defaults
  seo: {
    titleTemplate: string;
    defaultTitle: string;
    defaultDescription: string;
    twitterHandle?: string;
  };
}

/**
 * Current Site Configuration
 */
export const siteConfig: SiteConfig = {
  site: {
    name: "TrendsetterTales",
    tagline: "Where Style Meets Story",
    description: "TrendsetterTales brings you the latest fashion trends, beauty tips, and style inspiration. Explore curated looks, expert advice, and stories that define modern elegance.",
    url: process.env.NEXT_PUBLIC_SITE_URL || "https://trendsettertales.com",
    wordpressUrl: process.env.NEXT_PUBLIC_WORDPRESS_API_URL?.replace('/graphql', '') || "https://wp.trendsettertales.com",
    language: "en",
    locale: "en_US",
  },

  brand: {
    colors: {
      "primary": "#2C3E50",
      "secondary": "#F8F9FA",
      "accent": "#C9A885",
      "background": "#FFFFFF",
      "text": "#2C3E50",
      "textSecondary": "#6C757D"
},
    typography: {
      "headingFont": "Cormorant Garamond",
      "bodyFont": "Inter"
},
    logo: {
      text: "TRENDSETTERTALES",
      subtitle: "Where Style Meets Story",
    },
  },

  content: {
    postsPerPage: 12,
    relatedPostsCount: 5,
    excerptLength: 160,
    featuredImageRatio: "3:2",
    showAuthor: true,
    showDate: true,
    showCategories: true,
    showTags: true,
  },

  navigation: {
    header: [
      {
            "label": "Home",
            "href": "/"
      },
      {
            "label": "About",
            "href": "/about"
      }
],
    footer: {
      sections: [
        {
                "title": "Explore",
                "links": [
                        {
                                "label": "Beauty",
                                "href": "/category/beauty"
                        },
                        {
                                "label": "Nails",
                                "href": "/category/nails"
                        },
                        {
                                "label": "Outfits",
                                "href": "/category/outfits"
                        }
                ]
        },
        {
                "title": "Legal",
                "links": [
                        {
                                "label": "Privacy Policy",
                                "href": "/privacy"
                        },
                        {
                                "label": "Terms of Service",
                                "href": "/terms"
                        },
                        {
                                "label": "Disclaimer",
                                "href": "/disclaimer"
                        }
                ]
        },
        {
                "title": "Follow",
                "links": [
                        {
                                "label": "Pinterest",
                                "href": "https://pinterest.com/trendsettertales/",
                                "external": true
                        }
                ]
        }
],
    },
    menuCategories: [
      {
            "name": "Beauty",
            "slug": "beauty"
      },
      {
            "name": "Nails",
            "slug": "nails"
      },
      {
            "name": "Outfits",
            "slug": "outfits"
      }
],
  },

  social: {
    pinterest: "https://pinterest.com/trendsettertales/",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    tiktok: "",
    email: "",
  },

  analytics: {
    // googleAnalytics: "",
    // googleAdsense: "",
  },

  customScripts: {
    headScripts: `<script defer data-domain="trendsettertales.com" src="https://stats.tripleadigital.de/js/script.js"></script>`,
    // bodyStartScripts: "",
    // bodyEndScripts: "",
  },

  legal: {
    companyName: "Triple A Digital",
    contactEmail: "hey@trendsettertales.com",
    country: "Germany",
    jurisdiction: "Germany",
  },

  hero: {
    "title": "Discover Your Style",
    "subtitle": "Fashion, Beauty & Lifestyle Inspiration",
    "backgroundImage": "/images/hero-bg.jpg",
    "cta": {
        "text": "Explore Now",
        "href": "#categories"
    }
},

  persona: {
    "name": "Emma Sterling",
    "role": "Fashion & Beauty Curator",
    "bio": "Emma Sterling is a Copenhagen-based fashion curator and beauty enthusiast who bridges Scandinavian minimalism with modern elegance. With over a decade in the fashion industry, she helps women in their 30s and beyond discover their signature style through timeless pieces and sophisticated beauty rituals.",
    "story": "Emma's journey into fashion began unexpectedly during a rainy afternoon in Stockholm, where she stumbled into a vintage boutique and discovered a 1960s Marimekko dress that changed everything. That moment sparked a fascination with how clothing could tell stories and transform confidence. After studying fashion design in Copenhagen and working with several Nordic brands, she realized her true calling wasn't just creating fashion—it was helping women curate wardrobes that reflected their evolving identities.\n\nTurning 30 was a pivotal moment for Emma. She noticed how the fashion industry often overlooked women entering this exciting decade, treating it as if style should suddenly become conservative or invisible. Instead, Emma experienced her 30s as a time of clarity and confidence, where she finally understood what worked for her body, lifestyle, and values. This insight inspired her to create TrendsetterTales, a space where elegance meets practicality, and where sustainable choices don't mean sacrificing style.\n\nEmma's approach is deeply rooted in Scandinavian philosophy—less is more, quality over quantity, and beauty that enhances rather than masks. She believes that true style comes from understanding yourself, not chasing every trend. Whether she's exploring clean beauty brands in Copenhagen, hunting for the perfect cashmere sweater, or sharing her morning skincare ritual, Emma brings an authenticity that resonates with women who want to look polished without the pressure of perfection.\n\nToday, Emma splits her time between her minimalist apartment in Copenhagen's Vesterbro district and travels throughout Scandinavia, discovering emerging designers and time-tested beauty secrets. Her mission is simple: to prove that style after 30 isn't about following rules—it's about writing your own.",
    "expertise": [
        "Scandinavian Fashion Curation",
        "Sustainable Wardrobe Building",
        "Clean Beauty & Skincare",
        "Minimalist Style Coaching",
        "Timeless Accessory Selection"
    ],
    "quote": "Elegance is not about being noticed, it's about being remembered.",
    "achievements": [
        "Featured in Nordic Style Magazine's '30 Under 40' Influencers",
        "Collaborated with sustainable Scandinavian fashion brands including Arket and Filippa K",
        "Built a community of 50,000+ women embracing intentional style"
    ]
},
  seo: {
    titleTemplate: "%s | TrendsetterTales",
    defaultTitle: "TrendsetterTales - Where Style Meets Story",
    defaultDescription: "TrendsetterTales brings you the latest fashion trends, beauty tips, and style inspiration. Explore curated looks, expert advice, and stories that define modern elegance.",
  },
};

/**
 * Helper function to get nested config values safely
 */
export function getConfigValue<T>(path: string, defaultValue?: T): T | undefined {
  const keys = path.split('.');
  let value: any = siteConfig;

  for (const key of keys) {
    if (value && typeof value === 'object' && key in value) {
      value = value[key];
    } else {
      return defaultValue;
    }
  }

  return value as T;
}

/**
 * Get language configuration for current site
 */
export function getLanguage() {
  const langCode = siteConfig.site.language as SupportedLanguage;
  return getLanguageConfig(langCode);
}

/**
 * Get translated UI strings
 */
export function t() {
  return getLanguage().ui;
}
